exports.citiesList =     
    [{ 
        "state" : "Andaman & Nicobar Islands", 
        "cities" : [
            "South Andaman", 
            "North And Middle Andaman", 
            "Nicobar"
        ]
    },
    { 
        "state" : "Andhra Pradesh", 
        "cities" : [
            "Ananthapur", 
            "Cuddapah", 
            "Chittoor", 
            "Kurnool", 
            "Prakasam", 
            "West Godavari", 
            "Krishna", 
            "Nellore", 
            "Guntur", 
            "East Godavari", 
            "Vizag", 
            "Vizianagaram", 
            "Srikakulam"
        ]
    },
    { 
        "state" : "Arunachal Pradesh", 
        "cities" : [
            "Lower Dibang Valley", 
            "East Siang", 
            "Dibang Valley", 
            "West Siang", 
            "Lohit", 
            "Papum Pare", 
            "Tawang", 
            "West Kameng", 
            "East Kameng", 
            "Lower Subansiri", 
            "Changlang", 
            "Tirap", 
            "Kurung Kumey", 
            "Upper Siang", 
            "Upper Subansiri"
        ]
    },
    { 
        "state" : "Maharashtra", 
        "cities" : [
            "Jalna", 
            "Aurangabad", 
            "Beed", 
            "Jalgaon", 
            "Dhule", 
            "Nandurbar", 
            "Nashik", 
            "Nanded", 
            "Latur", 
            "Osmanabad", 
            "Hingoli", 
            "Parbhani", 
            "Kolhapur", 
            "Ratnagiri", 
            "Sindhudurg", 
            "Satara", 
            "Sangli", 
            "Mumbai", 
            "RaigarhMH", 
            "Thane", 
            "Akola", 
            "Washim", 
            "Amravati", 
            "Buldhana", 
            "Gadchiroli", 
            "Chandrapur", 
            "Nagpur", 
            "Gondia", 
            "Bhandara", 
            "Wardha", 
            "Yavatmal", 
            "Ahmed Nagar", 
            "Solapur", 
            "Pune"
        ]
    },
    {  
        "state" : "Assam", 
        "cities" : [
            "Lakhimpur", 
            "Dibrugarh", 
            "Dhemaji", 
            "Marigaon", 
            "Nagaon", 
            "Karbi Anglong", 
            "Golaghat", 
            "Sibsagar", 
            "Jorhat", 
            "Tinsukia", 
            "Karimganj", 
            "Hailakandi", 
            "Cachar", 
            "North Cachar Hills", 
            "Darrang", 
            "Sonitpur", 
            "Bongaigaon", 
            "Kokrajhar", 
            "Goalpara", 
            "Dhubri", 
            "Kamrup", 
            "Nalbari", 
            "Barpeta"
        ]
    },
    { 
        "state" : "Bihar", 
        "cities" : [
            "Begusarai", 
            "Khagaria", 
            "Darbhanga", 
            "Madhubani", 
            "Muzaffarpur", 
            "Samastipur", 
            "Sitamarhi", 
            "East Champaran", 
            "Supaul", 
            "Vaishali", 
            "Purnia", 
            "Araria", 
            "Katihar", 
            "Kishanganj", 
            "Madhepura", 
            "Saharsa", 
            "Saran", 
            "Siwan", 
            "Bhojpur", 
            "Sheohar", 
            "Gopalganj", 
            "West Champaran", 
            "Gaya", 
            "AurangabadBH", 
            "Arwal", 
            "Bhagalpur", 
            "Banka", 
            "Munger", 
            "Buxar", 
            "Jehanabad", 
            "Patna", 
            "Sheikhpura", 
            "Jamui", 
            "Lakhisarai", 
            "Nalanda", 
            "Nawada", 
            "Rohtas", 
            "Kaimur Bhabua"
        ]
    },
    { 
        "state" : "Manipur", 
        "cities" : [
            "Imphal West", 
            "Churachandpur", 
            "Chandel", 
            "Thoubal", 
            "Tamenglong", 
            "Ukhrul", 
            "Imphal East", 
            "Bishnupur", 
            "Senapati"
        ]
    },
    {  
        "state" : "Chandigarh", 
        "cities" : [
            "Chandigarh"
        ]
    },
    {  
        "state" : "Chattisgarh", 
        "cities" : [
            "Kanker", 
            "Bastar", 
            "Dantewada", 
            "BijapurCGH", 
            "Narayanpur", 
            "BilaspurCGH", 
            "Janjgirchampa", 
            "Korba", 
            "Durg", 
            "Rajnandgaon", 
            "Kawardha", 
            "Surguja", 
            "Raigarh", 
            "Jashpur", 
            "Koriya", 
            "Raipur", 
            "Mahasamund", 
            "Dhamtari", 
            "Gariaband"
        ]
    },
    { 
        "state" : "Dadra & Nagar Haveli", 
        "cities" : [
            "Dadra & Nagar Haveli"
        ]
    },
    { 
        "state" : "Meghalaya", 
        "cities" : [
            "West Garo Hills", 
            "East Garo Hills", 
            "Jaintia Hills", 
            "East Khasi Hills", 
            "South Garo Hills", 
            "Ri Bhoi", 
            "West Khasi Hills"
        ]
    },
    { 
        "state" : "Daman & Diu", 
        "cities" : [
            "Diu", 
            "Daman"
        ]
    },
    { 
        "state" : "Delhi", 
        "cities" : [
            "East Delhi", 
            "North East Delhi", 
            "North West Delhi", 
            "North Delhi", 
            "Central Delhi", 
            "New Delhi", 
            "South Delhi", 
            "South West Delhi", 
            "West Delhi"
        ]
    },
    {  
        "state" : "Mizoram", 
        "cities" : [
            "Aizawl", 
            "Mammit", 
            "Lunglei", 
            "Kolasib", 
            "Lawngtlai", 
            "Champhai", 
            "Saiha", 
            "Serchhip"
        ]
    },
    {  
        "state" : "Goa", 
        "cities" : [
            "South Goa", 
            "North Goa"
        ]
    },
    { 
        "state" : "Nagaland", 
        "cities" : [
            "Zunhebotto", 
            "Dimapur", 
            "Wokha", 
            "Phek", 
            "Mokokchung", 
            "Kiphire", 
            "Tuensang", 
            "Mon", 
            "Kohima", 
            "Peren", 
            "Longleng"
        ]
    },
    { 
        "state" : "Gujarat", 
        "cities" : [
            "Ahmedabad", 
            "Gandhi Nagar", 
            "Banaskantha", 
            "Mahesana", 
            "Surendra Nagar", 
            "Patan", 
            "Sabarkantha", 
            "Amreli", 
            "Rajkot", 
            "Junagadh", 
            "Bhavnagar", 
            "Jamnagar", 
            "Porbandar", 
            "Kachchh", 
            "Anand", 
            "Kheda", 
            "Surat", 
            "The Dangs", 
            "Tapi", 
            "Navsari", 
            "Vadodara", 
            "Bharuch", 
            "Narmada", 
            "Dahod", 
            "Panch Mahals", 
            "Valsad"
        ]
    },
    { 
        "state" : "Odisha", 
        "cities" : [
            "Ganjam", 
            "Gajapati", 
            "Kalahandi", 
            "Nuapada", 
            "Koraput", 
            "Rayagada", 
            "Nabarangapur", 
            "Malkangiri", 
            "Kandhamal", 
            "Boudh", 
            "Baleswar", 
            "Bhadrak", 
            "Kendujhar", 
            "Khorda", 
            "Puri", 
            "Cuttack", 
            "Jajapur", 
            "Kendrapara", 
            "Jagatsinghapur", 
            "Mayurbhanj", 
            "Nayagarh", 
            "Balangir", 
            "Sonapur", 
            "Angul", 
            "Dhenkanal", 
            "Sambalpur", 
            "Bargarh", 
            "Jharsuguda", 
            "Debagarh", 
            "Sundergarh"
        ]
    },
    { 
        "state" : "Pondicherry", 
        "cities" : [
            "Pondicherry", 
            "Mahe", 
            "Karaikal"
        ]
    },
    {  
        "state" : "Lakshadweep", 
        "cities" : [
            "Lakshadweep"
        ]
    },
    {  
        "state" : "Haryana", 
        "cities" : [
            "Ambala", 
            "Yamuna Nagar", 
            "Panchkula", 
            "Bhiwani", 
            "Faridabad", 
            "Gurgaon", 
            "Rewari", 
            "Mahendragarh", 
            "Hisar", 
            "Sirsa", 
            "Fatehabad", 
            "Karnal", 
            "Panipat", 
            "Jind", 
            "Kaithal", 
            "Kurukshetra", 
            "Jhajjar", 
            "Rohtak", 
            "Sonipat"
        ]
    },
    {  
        "state" : "Himachal Pradesh", 
        "cities" : [
            "Chamba", 
            "Kangra", 
            "Bilaspur HP", 
            "HamirpurHP", 
            "Una", 
            "Mandi", 
            "Kullu", 
            "Lahul & Spiti", 
            "Kinnaur", 
            "Shimla", 
            "Sirmaur", 
            "Solan"
        ]
    },
    { 
        "state" : "Jammu & Kashmir", 
        "cities" : [
            "Bandipur", 
            "Baramulla", 
            "Kupwara", 
            "Jammu", 
            "Kathua", 
            "Udhampur", 
            "Poonch", 
            "Kargil", 
            "Leh", 
            "Rajauri", 
            "Reasi", 
            "Srinagar", 
            "Budgam", 
            "Ananthnag", 
            "Shopian", 
            "Pulwama", 
            "Kulgam", 
            "Doda"
        ]
    },
    {  
        "state" : "Punjab", 
        "cities" : [
            "Ropar", 
            "Mohali", 
            "Rupnagar", 
            "Patiala", 
            "Ludhiana", 
            "Fatehgarh Sahib", 
            "Sangrur", 
            "Barnala", 
            "Amritsar", 
            "Tarn Taran", 
            "Bathinda", 
            "Mansa", 
            "Muktsar", 
            "Moga", 
            "Faridkot", 
            "Firozpur", 
            "Fazilka", 
            "Gurdaspur", 
            "Pathankot", 
            "Hoshiarpur", 
            "Nawanshahr", 
            "Jalandhar", 
            "Kapurthala"
        ]
    },
    {  
        "state" : "Jharkhand", 
        "cities" : [
            "Dhanbad", 
            "Bokaro", 
            "Giridh", 
            "Hazaribag", 
            "Chatra", 
            "Ramgarh", 
            "Koderma", 
            "Latehar", 
            "Garhwa", 
            "Palamau", 
            "Ranchi", 
            "Gumla", 
            "Simdega", 
            "Lohardaga", 
            "West Singhbhum", 
            "Khunti", 
            "Deoghar", 
            "Godda", 
            "Jamtara", 
            "Sahibganj", 
            "Dumka", 
            "Pakur", 
            "Seraikelakharsawan", 
            "East Singhbhum"
        ]
    },
    {  
        "state" : "Rajasthan", 
        "cities" : [
            "Ajmer", 
            "Rajsamand", 
            "Bhilwara", 
            "Chittorgarh", 
            "Banswara", 
            "Dungarpur", 
            "Kota", 
            "Baran", 
            "Jhalawar", 
            "Bundi", 
            "Tonk", 
            "Udaipur", 
            "Alwar", 
            "Bharatpur", 
            "Dholpur", 
            "Jaipur", 
            "Dausa", 
            "Sawai Madhopur", 
            "Karauli", 
            "Barmer", 
            "Bikaner", 
            "Churu", 
            "Jhujhunu", 
            "Jodhpur", 
            "Jaisalmer", 
            "Nagaur", 
            "Pali", 
            "Sikar", 
            "Sirohi", 
            "Jalor", 
            "Ganganagar", 
            "Hanumangarh"
        ]
    },
    { 
        "state" : "Karnataka", 
        "cities" : [
            "Bangalore", 
            "Bangalore Rural", 
            "Ramanagar", 
            "Bagalkot", 
            "Bijapur", 
            "Belgaum", 
            "Davangere", 
            "Bellary", 
            "Bidar", 
            "Dharwad", 
            "Gadag", 
            "Koppal", 
            "Yadgir", 
            "Gulbarga", 
            "Haveri", 
            "Uttara Kannada", 
            "Raichur", 
            "Chickmagalur", 
            "Chitradurga", 
            "Hassan", 
            "Kodagu", 
            "Chikkaballapur", 
            "Kolar", 
            "Mandya", 
            "Dakshina Kannada", 
            "Udupi", 
            "Mysore", 
            "Chamrajnagar", 
            "Shimoga", 
            "Tumkur", 
            "Hubli", 
            "Mangalore"
        ]
    },
    {  
        "state" : "Sikkim", 
        "cities" : [
            "East Sikkim", 
            "West Sikkim", 
            "South Sikkim", 
            "North Sikkim"
        ]
    },
    { 
        "state" : "Kerala", 
        "cities" : [
            "Wayanad", 
            "Kozhikode", 
            "Malappuram", 
            "Kannur", 
            "Kasargod", 
            "Palakkad", 
            "Alappuzha", 
            "Ernakulam", 
            "Kottayam", 
            "Pathanamthitta", 
            "Idukki", 
            "Thrissur", 
            "Kollam", 
            "Thiruvananthapuram"
        ]
    },
    { 
        "state" : "Tamil Nadu", 
        "cities" : [
            "Chennai", 
            "Vellore", 
            "Tiruvannamalai", 
            "Kanchipuram", 
            "Tiruvallur", 
            "Villupuram", 
            "Cuddalore", 
            "Coimbatore", 
            "Dharmapuri", 
            "Salem", 
            "Erode", 
            "Karur", 
            "Namakkal", 
            "Krishnagiri", 
            "Nilgiris", 
            "Dindigul", 
            "Kanyakumari", 
            "Sivaganga", 
            "Ramanathapuram", 
            "Tuticorin", 
            "Tirunelveli", 
            "Madurai", 
            "Theni", 
            "Virudhunagar", 
            "Ariyalur", 
            "Tiruchirappalli", 
            "Pudukkottai", 
            "Tiruvarur", 
            "Thanjavur", 
            "Nagapattinam", 
            "Perambalur"
        ]
    },
    {  
        "state" : "Madhya Pradesh", 
        "cities" : [
            "Seoni", 
            "Balaghat", 
            "Mandla", 
            "Dindori", 
            "Bhopal", 
            "Raisen", 
            "Chhatarpur", 
            "Tikamgarh", 
            "Panna", 
            "Betul", 
            "Chhindwara", 
            "Hoshangabad", 
            "Narsinghpur", 
            "Harda", 
            "Satna", 
            "Rewa", 
            "Damoh", 
            "Sagar", 
            "Anuppur", 
            "Umaria", 
            "Shahdol", 
            "Sidhi", 
            "Singrauli", 
            "Vidisha", 
            "Ashok Nagar", 
            "Shivpuri", 
            "Guna", 
            "Gwalior", 
            "Datia", 
            "Bhind", 
            "Morena", 
            "Sheopur", 
            "Indore", 
            "Dewas", 
            "Dhar", 
            "Katni", 
            "Jabalpur", 
            "East Nimar", 
            "West Nimar", 
            "Barwani", 
            "Khandwa", 
            "Burhanpur", 
            "Khargone", 
            "Neemuch", 
            "Mandsaur", 
            "Jhabua", 
            "Ratlam", 
            "Alirajpur", 
            "Sehore", 
            "Rajgarh", 
            "Ujjain", 
            "Shajapur"
        ]
    },
    {  
        "state" : "Telangana", 
        "cities" : [
            "Adilabad", 
            "Warangal", 
            "Karim Nagar", 
            "Mahabub Nagar", 
            "KVRangareddy", 
            "Medak", 
            "Nalgonda", 
            "Nizamabad", 
            "Hyderabad", 
            "Khammam", 
            "Secunderabad"
        ]
    },
    {  
        "state" : "Tripura", 
        "cities" : [
            "South Tripura", 
            "West Tripura", 
            "Dhalai", 
            "North Tripura"
        ]
    },
    { 
        "state" : "Uttar Pradesh", 
        "cities" : [
            "Agra", 
            "Aligarh", 
            "Hathras", 
            "Bulandshahr", 
            "Gautam Buddha Nagar", 
            "Etah", 
            "Firozabad", 
            "Etawah", 
            "Auraiya", 
            "Jhansi", 
            "Jalaun", 
            "Lalitpur", 
            "Mainpuri", 
            "Mathura", 
            "Azamgarh", 
            "Allahabad", 
            "Kaushambi", 
            "Ghazipur", 
            "Jaunpur", 
            "Sonbhadra", 
            "Mirzapur", 
            "Pratapgarh", 
            "Varanasi", 
            "Chandauli", 
            "Sant Ravidas Nagar", 
            "Pilibhit", 
            "Bareilly", 
            "Bijnor", 
            "Budaun", 
            "Hardoi", 
            "Kheri", 
            "Meerut", 
            "Bagpat", 
            "Moradabad", 
            "Jyotiba Phule Nagar", 
            "Rampur", 
            "Muzaffarnagar", 
            "Saharanpur", 
            "Shahjahanpur", 
            "Mau", 
            "Shrawasti", 
            "Bahraich", 
            "Ballia", 
            "Siddharthnagar", 
            "Sant Kabir Nagar", 
            "Basti", 
            "Deoria", 
            "Kushinagar", 
            "Gonda", 
            "Balrampur", 
            "Gorakhpur", 
            "Maharajganj", 
            "Banda", 
            "Chitrakoot", 
            "Mahoba", 
            "Hamirpur", 
            "Kannauj", 
            "Farrukhabad", 
            "Fatehpur", 
            "Kanpur Nagar", 
            "Unnao", 
            "Kanpur Dehat", 
            "Barabanki", 
            "Faizabad", 
            "Ambedkar Nagar", 
            "Ghaziabad", 
            "Lucknow", 
            "Raebareli", 
            "Sitapur", 
            "Sultanpur"
        ]
    },
    { 
        "state" : "Uttarakhand", 
        "cities" : [
            "Haridwar", 
            "Almora", 
            "Bageshwar", 
            "Chamoli", 
            "Rudraprayag", 
            "Dehradun", 
            "Udham Singh Nagar", 
            "Nainital", 
            "Champawat", 
            "Pauri Garhwal", 
            "Pithoragarh", 
            "Tehri Garhwal", 
            "Uttarkashi"
        ]
    },
    { 
        "state" : "West Bengal", 
        "cities" : [
            "Kolkata", 
            "North 24 Parganas", 
            "South 24 Parganas", 
            "Birbhum", 
            "Murshidabad", 
            "Nadia", 
            "Cooch Behar", 
            "Jalpaiguri", 
            "Darjiling", 
            "Malda", 
            "South Dinajpur", 
            "North Dinajpur", 
            "Bardhaman", 
            "Bankura", 
            "West Midnapore", 
            "East Midnapore", 
            "Hooghly", 
            "Howrah", 
            "Medinipur", 
            "Puruliya"
        ]
    }];